apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-website-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-website
  template:
    metadata:
      labels:
        app: static-website
    spec:
      containers:
        - name: static-website-container  # ✅ FIXED (removed underscore)
          image: kirubarp/final_repo:latest  # Your DockerHub repo
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: static-website-service
spec:
  type: LoadBalancer
  selector:
    app: static-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

