apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-website-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-website
  template:
    metadata:
      labels:
        app: static-website
    spec:
      containers:
        - name: static-website-container
          image: kirubarp/final_repo:latest  # DockerHub repo
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: static-website-service
spec:
  type: NodePort  # ✅ FIXED: Changed from LoadBalancer to NodePort
  selector:
    app: static-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # ✅ Set NodePort to access from Minikube
